Update README.md
graphprotocol/common-ts pull request #57
Opened 2021-01-06 17:21 UTC by dtourek

cheers! :)

2021-01-06 17:59 UTC, Jannis requested changes

2021-01-06 17:59 UTC, Jannis commented on packages/common-ts/README.md
> +Copyright &copy; 2021 The Graph Foundation.
Good eye 😄

Can we make that 2020-2021 and also update the years in `LICENSE`?

2021-01-07 20:01 UTC, dtourek commented on packages/common-ts/README.md
> +Copyright &copy; 2021 The Graph Foundation.
sure :+1:  :)

2021-04-15 22:47 UTC, Jannis approved these changes

2021-04-15 22:48 UTC, merged