Added BytesWriter
graphprotocol/common-ts pull request #67
Opened 2021-05-06 17:00 UTC by That3Percent

2021-05-06 20:29 UTC, Jannis requested changes
There's also a few linter warnings/errors in this PR.

2021-05-06 20:29 UTC, Jannis commented on packages/common-ts/src/util/bytes.ts
> +    }
Have you considered https://stackoverflow.com/a/55260916 as an alternative to looping ourselves? I wonder if it might render `BytesWriter` unnecessary even.

I could imagine just having two helper functions:

```ts
export function arrayFromHex(s: string): Uint8Array
export function concatBtes(a: Uint8Array, b: Uint8Array): Uint8Array
```

Because as far as I know, the only way to concatenate byte arrays in JS is something like:
```js
var c = new Uint8Array(a.length + b.length);
c.set(a);
c.set(b, a.length);
```
which we wouldn't want to do write every time combine some hex strings. What do you think?

2021-05-06 20:37 UTC, Jannis commented on packages/common-ts/src/util/bytes.ts
> +    }
@That3Percent I wonder how creating a new `Uint8Array` on concat compares to your manual parsing of ints and adding them to the fixed-size `Uint8Array`... I could see how what you're doing is faster but I'm not sure. `ArrayBuffer#set` might be really efficient.

2021-05-06 20:48 UTC, That3Percent commented on packages/common-ts/src/util/bytes.ts
> +    }
The problem this the API you are proposing `export function concatBytes(a: Uint8Array, b: Uint8Array): Uint8Array` is that this would be `O(n^2)`. So _some_ implementation of `BytesWriter` is still necessary to maintain a write offset into a pre-sized buffer. (This is something I had to do a lot when working with webgl)

What is up for consideration is the implementation of `writeHex`. I'd like to try a couple of things and taking advantage of `Buffer.from(s, 'hex')` is one of them. There's a toss-up here about what the optimizer might be able to do with this loop as-is. But, I figured that performance could wait until after we have a first version and this should suffice for a first pass. (Hence the TODO).

In any case, I'll fix the linter errors.

2021-05-06 20:58 UTC, Jannis commented on packages/common-ts/src/util/bytes.ts
> +    }
Hehe. I'm fine going with your approach and agree optimizing ca follow if necessary.

2021-05-06 20:59 UTC, Jannis approved these changes
Once the linter issues are fixed, this is good to go from my side.

2021-05-07 12:35 UTC, Jannis commented
Not sure why the CI build has been running `yarn install` for 15 minutes... I'll assume the code here is fine and merge it.

2021-05-07 12:35 UTC, merged